import streamlit as st

st.markdown("### 🐣 1학년 2반 English Classroom")
st.caption("Applications for the May 29 Class")

url="https://github.com/MK316/250529/raw/main/images/bg01-rose.jpg"
st.image(url, caption="Grammar makes meaning clear. (This image is generated by GPT4o.)")
